# fly.toml file generated for happypet on 2023-03-22T21:28:56-05:00

app = "happypet"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "bog"
processes = []

[build]
  image = "ozzyta/dockimages:happypet"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
